vuestorefront/storefront-nuxt3-boilerplate

apps/web/pages/search.vue
https://vsf.atlassian.net/browse/SV-40
This PR is adding the search dedicated page. This page is very similar to the category page. Differences are:
- no breadcrumbs
- no category tree
- heading changed to `Results for ${phrase}`
=> feat: add search page

README.md
Add note about WIP status.
I want to make the repo public to share with some of our OS partners.
=> chore: update README.md with WIP notice

apps/web/layouts/default.vue
https://vsf.atlassian.net/browse/SV-83
=> fix: align browser products button

apps/web/components/ProductAccordion/ProductAccordion.vue, apps/web/components/ProductAccordion/__tests__/ProductAccordion.spec.ts, apps/web/components/ProductAccordion/types.ts, apps/web/components/ui/AccordionItem/AccordionItem.vue, apps/web/components/ui/AccordionItem/__tests__/AccordionItem.spec.ts, apps/web/components/ui/AccordionItem/types.ts, apps/web/components/ui/Review/Review.vue, apps/web/components/ui/Review/__tests__/Review.spec.ts, apps/web/components/ui/Review/types.ts, apps/web/composables/useProductReviews/__tests__/productReviews.mock.ts, apps/web/composables/useProductReviews/__tests__/useProductReviews.spec.ts, apps/web/composables/useProductReviews/index.ts, apps/web/composables/useProductReviews/types.ts, apps/web/composables/useProductReviews/useProductReviews.ts, apps/web/pages/product/[slug].vue, apps/web/vue-test-utils.extend.js
https://vsf.atlassian.net/browse/SV-29
=> feat: product reviews accordion [SV-29]

apps/web/package.json, yarn.lock
https://vsf.atlassian.net/browse/SV-82
Fonts were properly working in dev mode but for prod mode they were receiving 404 error. Updating nuxt package helped with this issue.
By the way some other packages are updated.
=> fix: not loading fonts in prod mode

apps/web/__tests__/support/pageObjects/CartPageObject.ts, apps/web/__tests__/support/pageObjects/ProductDetailPageObject.ts, apps/web/components/ui/QuantitySelector/QuantitySelector.vue
https://vsf.atlassian.net/browse/SV-92
Fix for labels. One was missing, others were not translated.
Also changed data test id attributes from camel case to kebab case like it should be.
=> fix: adjust quantity selector labels

apps/web/components/ui/Footer.vue
https://vsf.atlassian.net/browse/SV-90
Added missing titles for social icons in the footer.
=> fix: add titles for social links

apps/web/components/CartPageContent/CartPageContent.vue, apps/web/components/ui/Display/Display.vue, apps/web/components/ui/Hero/Hero.vue, apps/web/components/ui/ProductCard/ProductCard.vue
https://vsf.atlassian.net/browse/SV-91
Fixes for best practices and CLS.
=> fix: add missing widht and height attributes for images

.github/workflows/code-quality.yaml, .github/workflows/initial-setup.yaml, apps/server/sonar-project.properties, apps/web/sonar-project.properties
https://vsf.atlassian.net/browse/SV-70
=> chore: sonarcloud [SV-70]

GUIDE.md, README.md
[https://vsf.atlassian.net/browse/SV-61](SV-61)
This PR provides Boilerplate README and GUIDE files with related to the Nuxt/Vue contents.
=> docs(sv-61): initial guide and readme files

apps/web/components/AddressForm/AddressForm.vue, apps/web/components/AddressForm/__tests__/AddressForm.spec.ts, apps/web/components/AddressForm/types.ts, apps/web/components/CheckoutAddress/CheckoutAddress.vue, apps/web/components/CheckoutAddress/__tests__/CheckoutAddress.spec.ts, apps/web/components/CheckoutAddress/types.ts, apps/web/components/ui/Form/FormHelperText.vue, apps/web/components/ui/Form/__tests__/FormHelperText.spec.ts, apps/web/pages/checkout.vue
https://vsf.atlassian.net/browse/SV-21
https://vsf.atlassian.net/browse/SV-22
Billing and shipping address
=> feat: billing and shipping address

.github/workflows/e2e-tests.yaml, apps/web/__tests__/support/commands.ts, apps/web/__tests__/support/pageObjects/CartPageObject.ts, apps/web/__tests__/support/pageObjects/CheckoutPageObject.ts, apps/web/__tests__/support/pageObjects/HomePageObject.ts, apps/web/__tests__/support/pageObjects/ProductDetailPageObject.ts, apps/web/__tests__/test/smoke/cartPage.cy.ts, apps/web/__tests__/test/smoke/checkoutPage.cy.ts, apps/web/__tests__/test/smoke/homePage.cy.ts, apps/web/__tests__/test/smoke/productDetailPage.cy.ts, apps/web/__tests__/test/smoke/productListPage.cy.ts, apps/web/components/Gallery/Gallery.vue, package.json, yarn.lock
- [x ] 📖 Documentation (updates to the documentation, readme or JSDoc annotations)
- [ x] 👌 Enhancement (improving an existing functionality like performance)
- [x ] ✨ New feature (a non-breaking change that adds functionality)
Updated tests to work with PRs and checking vue boilerplate
- [ x] I have linked an issue or discussion.
- [x ] I have updated the documentation accordingly.
=> feat: update tests to work on vue boilerplate

apps/web/lang/en.json, apps/web/layouts/account.vue, apps/web/pages/my-account/billing-details.vue, apps/web/pages/my-account/index.vue, apps/web/pages/my-account/my-orders.vue, apps/web/pages/my-account/personal-data.vue, apps/web/pages/my-account/returns.vue, apps/web/pages/my-account/shipping-details.vue, apps/web/utils/paths.ts
https://vsf.atlassian.net/browse/SV-108
- add new layout `account` with sub routing for every sub page e.g (returns, shipping details)
- add translation into `en.json` file
- dynamic breadcrumbs based on if we are in route `/my-accoun` or in sub page `/my-account/shipping-details`
Initial view on `/my-account` url 
When selecting any account section
=> feat: add account layout and subpages [SV-108]

apps/web/components/AddressForm/AddressForm.vue
https://vsf.atlassian.net/browse/SV-117
=> fix: select value in form in checkout page

.github/workflows/e2e-tests.yaml, apps/web/__tests__/support/commands.ts, apps/web/__tests__/support/pageObjects/HomePageObject.ts, apps/web/__tests__/support/pageObjects/ProductListPageObject.ts, apps/web/__tests__/test/smoke/cartPage.cy.ts, apps/web/__tests__/test/smoke/checkoutPage.cy.ts, apps/web/__tests__/test/smoke/homePage.cy.ts, apps/web/__tests__/test/smoke/productDetailPage.cy.ts, apps/web/__tests__/test/smoke/productListPage.cy.ts, package.json, yarn.lock
https://vsf.atlassian.net/browse/SV-107
- format a bit test files
- add cypress github action
- add concurrently and wait-on so we will be sure that actually website is served so we could run tests
- add uploading screenshots on failing tests
=> fix: e2e tests [SV-107]

apps/web/components/Gallery/Gallery.vue, apps/web/components/ui/CartProductCard/CartProductCard.vue, apps/web/components/ui/CategoryCard/CategoryCard.vue, apps/web/components/ui/Display/Display.vue, apps/web/components/ui/Hero/Hero.vue, apps/web/components/ui/ProductCard/ProductCard.vue, apps/web/pages/order/failed.vue, apps/web/pages/order/success.vue
https://vsf.atlassian.net/browse/SV-111
This PR is reducing image sizes. For the homepage, the size is reduced from 634kB to 123kB.
=> perf: reduce image size

apps/web/__tests__/test/smoke/homePage.cy.ts
=> feat: skipping tests until fixing

apps/web/components/Gallery/Gallery.vue, apps/web/nuxt.config.ts
Quick fix for displaying gallery image.
=> fix: adjust image for gallery

apps/web/components/CheckoutPayment/CheckoutPayment.vue
https://vsf.atlassian.net/browse/SV-124
PayPal payment method was enabled. It should be disabled by default.
=> fix: disable paypal payment method

apps/web/components/CategoryEmptyState/CategoryEmptyState.vue, apps/web/components/ui/Footer.vue, apps/web/components/ui/NavbarBottom.vue, apps/web/components/ui/NavbarTop.vue, apps/web/composables/useAccount/__tests__/useAccount.spec.ts, apps/web/composables/useAccount/index.ts, apps/web/composables/useAccount/types.ts, apps/web/composables/useAccount/useAccount.ts, apps/web/composables/useCart/__tests__/useCart.spec.ts, apps/web/composables/useCart/types.ts, apps/web/composables/useCart/useCart.ts, apps/web/lang/en.json, apps/web/layouts/account.vue, apps/web/layouts/checkout.vue, apps/web/layouts/default.vue
https://vsf.atlassian.net/browse/SV-96
- update a bit design on bottom nav
- move modal and search button from NavBarBottom
- create account button with dropdown in NavBarTop
- on mobile show `Account` button in NavBarBottom
- add composable that uses fake/fixed data for now, once SDK will provide specific methods `new Promise` can be replaced
- add tests to `useAccount` and `useCard`
- change `useCard` to conform style of writing in nuxt project, use `fetchCard` instead of `getCard`
=> feat: add button and dropdown for account [SV-96]

apps/web/components/Gallery/Gallery.vue, apps/web/components/ui/Hero/Hero.vue, apps/web/components/ui/ProductCard/ProductCard.vue
https://vsf.atlassian.net/browse/SV-114
Adding preload for images that are responsible for LCP is boosting performance greatly.
=> perf: reduce lcp

apps/web/layouts/account.vue
=> fix: build project

apps/web/layouts/default.vue
followup https://github.com/vuestorefront/storefront-nuxt3-boilerplate/pull/76
- Add missing translation function for logout
- Do logout button focusable, change into button tag
- check if logout button with strings not transpiled target translations
=> fix: account dropdown

apps/web/layouts/auth.vue
Layout that will be used for login/register/forget password pages
=> feat: add auth layout [SV-101]

apps/web/components/AccountData/AccountData.vue, apps/web/components/AccountData/__tests__/AccountData.spec.ts, apps/web/components/AccountData/types.ts, apps/web/components/AccountForms/AccountFormsName.vue, apps/web/components/AccountForms/AccountFormsPassword.vue, apps/web/components/AccountForms/__tests__/AccountFormsName.spec.ts, apps/web/components/AccountForms/__tests__/AccountFormsPassword.spec.ts, apps/web/components/AccountForms/types.ts, apps/web/components/AddressForm/AddressForm.vue, apps/web/components/ContactInformation/ContactInformationForm.vue, apps/web/components/ui/NavbarBottom.vue, apps/web/lang/en.json, apps/web/layouts/account.vue, apps/web/pages/my-account/billing-details.vue, apps/web/pages/my-account/personal-data.vue, apps/web/pages/my-account/shipping-details.vue
https://vsf.atlassian.net/browse/SV-97
Account settings for my account
=> feat: account settings

apps/web/__tests__/test/smoke/productListPage.cy.ts
Skipped this test as it was flaky
=> chore: skip flaky test

apps/web/components/ui/Alert/Alert.vue, apps/web/components/ui/Alert/types.ts, apps/web/components/ui/Form/FormLabel.vue, apps/web/components/ui/Form/FormPasswordInput.vue, apps/web/lang/en.json, apps/web/pages/login.vue
https://vsf.atlassian.net/browse/SV-101
clean up Alert component a bit and add "neutral" variant
add FormPasswordInput
=> feat: login page [SV-101]

apps/web/__tests__/support/pageObjects/CheckoutPageObject.ts, apps/web/__tests__/support/pageObjects/ProductListPageObject.ts, apps/web/components/CategoryFilters/types.ts, apps/web/components/CategorySidebar/types.ts, apps/web/components/ui/Search.vue, apps/web/composables/useHandleError/useHandleError.ts, apps/web/composables/useProductRecommended/types.ts
this PR fixes few issues reported by sonarcloud:
=> fix: sonarcloud issues

apps/web/components/ui/Breadcrumbs/Breadcrumbs.vue
https://vsf.atlassian.net/browse/SV-145
Fixed breadcrumbs overlap with other element
=> fix: breadcrumbs overlap

apps/web/composables/useCustomerOrder/__tests__/useCustomer.spec.ts, apps/web/composables/useCustomerOrder/index.ts, apps/web/composables/useCustomerOrder/types.ts, apps/web/composables/useCustomerOrder/useCustomerOrder.ts, apps/web/pages/my-account/my-orders.vue, apps/web/pages/my-account/personal-data.vue
https://vsf.atlassian.net/browse/SV-118
Since we don't know model data for account order, I prepared bare minimum of data based on figma designs, missing that can/should be fixed in order view page
=> feat: add useCustomerOrders composable [SV-118]

apps/web/composables/useCustomerReturns/__tests__/useCustomerReturns.spec.ts, apps/web/composables/useCustomerReturns/index.ts, apps/web/composables/useCustomerReturns/types.ts, apps/web/composables/useCustomerReturns/useCustomerReturns.ts, apps/web/pages/my-account/returns.vue
https://vsf.atlassian.net/browse/SV-119
composable for customer returns
=> feat: useCustomerReturns

apps/web/layouts/account.vue
https://vsf.atlassian.net/browse/SV-116
mobile view for my account
=> feat: mobile view for my account

apps/web/components/CheckoutAddress/CheckoutAddress.vue, apps/web/components/ContactInformation/ContactInformation.vue, apps/web/components/ShippingMethod/ShippingMethod.vue, apps/web/components/ui/Modal/Modal.vue, apps/web/components/ui/Modal/types.ts, apps/web/layouts/default.vue, apps/web/pages/my-account/billing-details.vue, apps/web/pages/my-account/my-orders/[id].vue, apps/web/pages/my-account/personal-data.vue, apps/web/pages/my-account/shipping-details.vue, apps/web/pages/signup.vue
https://vsf.atlassian.net/browse/SV-158
Create wrapper for `SfModal` so we would have scrollbar inside modal for smaller screen height
=> fix: modal for mobiles have scrollbar [SV-158]

apps/web/pages/my-account/billing-details.vue
https://vsf.atlassian.net/browse/SV-174
A quick fix for disabling not needed checkbox in billing address in my account page.
=> fix: remove checkbox from address modal in my account

apps/web/lang/en.json, apps/web/layouts/account.vue, apps/web/pages/my-account/billing-details.vue, apps/web/pages/my-account/my-orders.vue, apps/web/pages/my-account/personal-data.vue, apps/web/pages/my-account/returns.vue, apps/web/pages/my-account/shipping-details.vue
https://vsf.atlassian.net/browse/SV-159
Fix couple of visual issues 
1. Left sidebar height
Before
After
2. Heading order
Before
After
3. Orders table
Before
After
4. Divider causing horizontal scrollbar
Before 
After
5. Missing translation "List of orders"
=> fix: account views [SV-159]

apps/web/components/ui/CategoryCard/CategoryCard.vue, apps/web/components/ui/Footer.vue, apps/web/lang/en.json, apps/web/layouts/default.vue
fixes accessibility issues reported by [Pagespeed Insights](https://pagespeed.web.dev/analysis/https-boilerplate-nuxt-europe-west1-gcp-storefrontcloud-io/bmsj7iqah8?form_factor=mobile):
=> fix: accessibility issues

apps/web/__tests__/fixtures/account.json, apps/web/__tests__/support/commands.ts, apps/web/__tests__/support/e2e.ts, apps/web/__tests__/support/pageObjects/HomePageObject.ts, apps/web/__tests__/support/pageObjects/LoginPageObject.ts, apps/web/__tests__/support/pageObjects/PasswordPageObject.ts, apps/web/__tests__/support/pageObjects/ProductDetailPageObject.ts, apps/web/__tests__/support/pageObjects/SignupPageObject.ts, apps/web/__tests__/test/smoke/cartPage.cy.ts, apps/web/__tests__/test/smoke/checkoutPage.cy.ts, apps/web/__tests__/test/smoke/homePage.cy.ts, apps/web/__tests__/test/smoke/loginPage.cy.ts, apps/web/__tests__/test/smoke/passwordPage.cy.ts, apps/web/__tests__/test/smoke/signupPage.cy.ts, apps/web/__tests__/tsconfig.json, apps/web/app.vue, apps/web/components/RenderContentProductSlider/RenderContentProductSlider.vue, apps/web/cypress.config.ts, apps/web/layouts/default.vue, apps/web/package.json, apps/web/pages/login.vue, apps/web/pages/reset-password-success.vue, apps/web/pages/signup.vue, package.json, turbo.json, yarn.lock
added some tests for new pages in bp. On the next pr i will work on parrael tests in githubactions
added some tests for new pages in bp. On the next pr i will work on parrael tests in githubactions
some tests have waits. I know its not good practice but there is some issue with logic under buttons do not loading fast enought for cypress. We can work on that.
=> feat: add some tests and fix others

apps/web/__tests__/fixtures/account.json, apps/web/__tests__/support/commands.ts, apps/web/__tests__/support/e2e.ts, apps/web/__tests__/support/pageObjects/HomePageObject.ts, apps/web/__tests__/support/pageObjects/LoginPageObject.ts, apps/web/__tests__/support/pageObjects/PasswordPageObject.ts, apps/web/__tests__/support/pageObjects/ProductDetailPageObject.ts, apps/web/__tests__/support/pageObjects/SignupPageObject.ts, apps/web/__tests__/test/smoke/cartPage.cy.ts, apps/web/__tests__/test/smoke/checkoutPage.cy.ts, apps/web/__tests__/test/smoke/homePage.cy.ts, apps/web/__tests__/test/smoke/loginPage.cy.ts, apps/web/__tests__/test/smoke/passwordPage.cy.ts, apps/web/__tests__/test/smoke/productListPage.cy.ts, apps/web/__tests__/test/smoke/signupPage.cy.ts, apps/web/__tests__/tsconfig.json, apps/web/app.vue, apps/web/components/RenderContentProductSlider/RenderContentProductSlider.vue, apps/web/cypress.config.ts, apps/web/layouts/default.vue, apps/web/package.json, apps/web/pages/login.vue, apps/web/pages/reset-password-success.vue, apps/web/pages/signup.vue, package.json, turbo.json, yarn.lock
https://vsf.atlassian.net/browse/SV-207?atlOrigin=eyJpIjoiZWZhZDcxNGFjOTU1NDQ1NzhmZmM1OTM4YWFjMjEwYzAiLCJwIjoiaiJ9
=> feat: fix productlist tests [SV-207]

apps/web/layouts/account.vue
https://vsf.atlassian.net/browse/SV-172
Logout button on side panel should be visible only for mobile devices.
=> fix: remove logout button on my account page for larger devices

.github/workflows/code-quality.yaml
Simple update of GH actions for sonarcloud.
=> chore: update sonarcloud ci

apps/web/components/CategoryPageContent/CategoryPageContent.vue, apps/web/composables/useBreakpoints/index.ts, apps/web/composables/useBreakpoints/useBreakpoints.ts, apps/web/composables/useProductReviews/__tests__/useProductReviews.spec.ts, apps/web/layouts/account.vue, apps/web/utils/mediaQueries.ts
https://vsf.atlassian.net/browse/SV-224
Add useBreakpoints composable for handling media queries.
=> feat: add useBreadcrumbs composable

apps/web/components/AccountForms/AccountFormsPassword.vue, apps/web/components/AccountForms/types.ts
https://vsf.atlassian.net/browse/SV-173
Use single implementation of password form input.
=> fix: replace password inputs with dedicated component

README.md
Update README.md with new docs links.
=> docs: update README.md with new docs links

apps/web/composables/useCart/__tests__/useCart.spec.ts, apps/web/composables/useCart/types.ts, apps/web/composables/useCart/useCart.ts, apps/web/layouts/checkout.vue, apps/web/layouts/default.vue
Fixed the typo from 'fetchCard' to 'fetchCart'
=> fix: fetchCart typo
